experiment_name: xp1_cleaning

data:
  artefact_path: XP1_ARTEFACTS
  eeg_path: XP1_EEG

model:
  name: catboost
  channel_handling: channel_feature
  random_state: 42
  params:
    iterations: 1000
    verbose: false
    allow_writing_files: false

report:
  output_dir: outputs