experiment_name: xp2_cleaning_two_levels

data:
  artefact_path: XP1_ARTEFACTS
  eeg_path: XP1_EEG

preprocessing:
  physics_informed_artefacts: true

model:
  name: two_step_residual
  base_model: catboost
  channel_handling: channel_feature
  params:
    iterations: 1000
    verbose: false
    allow_writing_files: false
  first_features: lorentz
  residual_features: motion

report:
  output_dir: outputs